src/blog/urls.py
# blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.details, name='details'),
]

src/camp/urls.py
# camps/urls.py
from django.urls import path
from . import views

app_name = 'camps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:camp_id>/', views.details, name='details'),
    path('select-role/<int:camp_id>/', views.select_camp_role, name='select_camp_role'),
    path('register/<int:camp_id>/<str:register_type>/', views.register_stripe, name='register_new'),
    path('register-success/<path:payment_link>/', views.register_success, name='register_success'),
    path('edit-registration/<int:registration_id>/', views.edit_registration, name='edit_registration'),
    path('manager-panel/', views.manager_panel, name='manager_panel'),
    path('create/', views.create, name='create'),
]

src/f5rugby/urls.py
"""
URL configuration for f5rugby project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('preview/', views.preview, name='preview'),
    path('camps/', include('camp.urls')),
    path('health/', include('health.urls')),
    path('tours/', include('tour.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('account.urls')),
    path('deploy-webhook/', views.webhook_handler, name='deploy_webhook'),
    path('success/', views.success_page, name='success_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/camp/models.py
from django.db import models
from django.utils import timezone

class Camp(models.Model):
    title = models.CharField(max_length=100)
    address = models.CharField(max_length=150, blank=True)
    description = models.TextField()
    start_date = models.DateField()
    end_date = models.DateField()
    tags = models.CharField(max_length=255, blank=True)
    details = models.TextField(default='')
    crest = models.FileField(upload_to='camp_files/camp_crests/', blank=True)
    coach_price = models.IntegerField(blank=True, null=True)
    player_price = models.IntegerField(blank=True, null=True)
    coach_payment_link = models.CharField(max_length=255, blank=True)
    player_payment_link = models.CharField(max_length=255, blank=True)

    def __str__(self):
        return f"{self.title} - {self.start_date}"
    
class GeneralRegistration(models.Model):
    CAMP_REGISTER_TYPE_CHOICES = [
        ('coach', 'Coach'),
        ('player', 'Player'),
    ]
    camp = models.ForeignKey(Camp, on_delete=models.CASCADE)
    type = models.CharField(max_length=10, choices=CAMP_REGISTER_TYPE_CHOICES)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=20)
    club = models.CharField(max_length=100, blank=True)
    position = models.CharField(max_length=100, blank=True)
    birthday = models.DateField(blank=True, null=True)
    emergency_contact_first_name = models.CharField(max_length=100)
    emergency_contact_last_name = models.CharField(max_length=100)
    emergency_contact_email = models.EmailField()
    emergency_contact_phone = models.CharField(max_length=20)
    photo_release_form = models.FileField(upload_to='camp_files/photo_release_forms/', blank=True)
    liability_waiver = models.FileField(upload_to='camp_files/liability_waivers/', blank=True)
    registration_date = models.DateTimeField(default=timezone.now)
    has_paid = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name} - {self.camp.title} - {self.type} : {self.has_paid}"

src/camp/forms.py
from django import forms
from .models import GeneralRegistration, Camp

class CampForm(forms.ModelForm):
    class Meta:
        model = Camp
        fields = ['title', 'address', 'description', 'start_date', 'end_date', 'tags', 'details', 'crest', 'coach_price', 'player_price', 'coach_payment_link', 'player_payment_link']
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }

class PlayerRegistrationForm(forms.ModelForm):
    class Meta:
        model = GeneralRegistration
        fields = ['first_name', 'last_name', 'email', 'club', 'position', 'birthday', 'emergency_contact_first_name', 'emergency_contact_last_name', 'emergency_contact_email', 'emergency_contact_phone']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'}),
        }

class CoachRegistrationForm(forms.ModelForm):
    class Meta:
        model = GeneralRegistration
        fields = ['first_name', 'last_name', 'email', 'phone', 'club']

class ModifyPlayerRegistrationForm(forms.ModelForm):
    class Meta:
        model = GeneralRegistration
        fields = ['first_name', 'last_name', 'email', 'club', 'position', 'birthday', 'emergency_contact_first_name', 'emergency_contact_last_name', 'emergency_contact_email', 'emergency_contact_phone', 'photo_release_form', 'liability_waiver', 'has_paid']
        widgets = {
            'birthday': forms.DateInput(attrs={'type': 'date'}),
        }

class ModifyCoachRegistrationForm(forms.ModelForm):
    class Meta:
        model = GeneralRegistration
        fields = ['first_name', 'last_name', 'email', 'phone', 'club', 'photo_release_form', 'liability_waiver', 'has_paid']

src/camp/views.py
# camps/views.py
from django.contrib import messages
from django.shortcuts import render, redirect
from .models import Camp, GeneralRegistration
from account.decorators import manager_required
from django.contrib.auth.decorators import login_required
from .forms import PlayerRegistrationForm, CoachRegistrationForm, ModifyPlayerRegistrationForm, ModifyCoachRegistrationForm, CampForm

def index(request):
    all_camps = Camp.objects.order_by('start_date')
    context = {'camps': all_camps}
    return render(request, 'camps/index.html', context)

def details(request, camp_id):
    try:
        camp = Camp.objects.get(pk=camp_id)
    except Camp.DoesNotExist:
        messages.error(request, 'This camp does not exist.')
        return render(request, 'f5rugby/error.html')
    
    context ={
        'camp': camp,
    }
    return render(request, 'camps/details.html', context)

@login_required
@manager_required
def create(request):
    if request.method == 'POST':
        form = CampForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('camps:manager_panel')
    else:
        form = CampForm()
    return render(request, 'camps/create.html', {'form': form})


def select_camp_role(request, camp_id):
    context = {
        'camp_id': camp_id,
    }
    return render(request, 'camps/select_role.html', context)

def register_stripe(request, camp_id, register_type):
    payment_link = ''
    camp = None
    type_string = ''
    
    # Check if camp exists
    try:
        camp = Camp.objects.get(pk=camp_id)
    except Camp.DoesNotExist:
        messages.error(request, 'This camp does not exist.')
        return render(request, 'f5rugby/error.html')

    # Get the registration type from query parameters
    if register_type not in ['player', 'coach']:
        messages.error(request, 'Invalid register type.')
        return render(request, 'f5rugby/error.html')

    # Determine the form based on the registration type
    if register_type == 'player':
        payment_link = camp.player_payment_link
        type_string = 'players'
    elif register_type == 'coach':
        form = CoachRegistrationForm(request.POST or None)
        payment_link = camp.coach_payment_link
        type_string = 'coaches'

    context = {
        'camp': camp,
        'type_string': type_string,
        'payment_link': payment_link,
    }
    return redirect(payment_link)

def register(request, camp_id, register_type):
    payment_link = ''
    template_name = ''
    camp = None
    type_string = ''
    
    # Check if camp exists
    try:
        camp = Camp.objects.get(pk=camp_id)
    except Camp.DoesNotExist:
        messages.error(request, 'This camp does not exist.')
        return render(request, 'f5rugby/error.html')

    # Get the registration type from query parameters
    if register_type not in ['player', 'coach']:
        messages.error(request, 'Invalid register type.')
        return render(request, 'f5rugby/error.html')

    # Determine the form based on the registration type
    if register_type == 'player':
        form = PlayerRegistrationForm(request.POST or None)
        payment_link = camp.player_payment_link
        template_name = 'camps/register_player.html'
        type_string = 'players'
    elif register_type == 'coach':
        form = CoachRegistrationForm(request.POST or None)
        payment_link = camp.coach_payment_link
        template_name = 'camps/register_coach.html'
        type_string = 'coaches'

    # Process form
    if request.method == 'POST':
        if form.is_valid() and not request.POST.get('honeypot'):
            email = form.cleaned_data['email']
            # Check if there is already a registration with the same email under the same camp
            existing_registration = GeneralRegistration.objects.filter(camp=camp, email=email, type=register_type).exists()
            
            # Check for duplicate registration
            if existing_registration:
                messages.error(request, 'User with this email is already registered for this camp.')
            else:
                registration = form.save(commit=False)
                registration.camp = camp
                registration.type = register_type
                registration.save()
                return redirect('camps:register_success', payment_link=payment_link)
        else:
            messages.error(request, 'Ha! Bot.')
            return render(request, template_name, {'form': form})

    context = {
        'camp': camp,
        'type_string': type_string,
        'payment_link': payment_link,
        'form': form,
    }
    return render(request, template_name, context)

@login_required
@manager_required
def manager_panel(request):
    all_camps = Camp.objects.order_by('start_date')
    context = {
        'camps': all_camps,
    }
    return render(request, 'camps/manager/camp_list.html', context)


@login_required
@manager_required
def edit_registration(request, registration_id):
    try:
        registration = GeneralRegistration.objects.get(pk=registration_id)
    except GeneralRegistration.DoesNotExist:
        messages.error(request, 'This registrations does not exist.')
        return render(request, 'f5rugby/error.html')
    
    if registration.type == 'player':
        form_class = ModifyPlayerRegistrationForm
    elif registration.type == 'coach':
        form_class = ModifyCoachRegistrationForm
    else:
        messages.error(request, 'Unknown registration type.')
        return render(request, 'f5rugby/error.html')

    if request.method == 'POST':
        form = form_class(request.POST, request.FILES, instance=registration)
        if form.is_valid():
            form.save()
            return redirect('accounts:camps_admin') 
    else:
        form = form_class(instance=registration)

    return render(request, 'camps/manager/edit_registration.html', {'form': form})

def register_success(request, payment_link):
    # Will require the camp, and the type of registeration
    # Player or coach, redirect to according payment
    context = {
        'payment_link': payment_link,
    }
    return render(request, 'camps/register_success.html', context)

src/templates/camps/camps.html
<!-- templates/f5rugby/camps.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/cards.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Rugby Camps{% endblock %}
{% block description %}Join our rugby camps for a comprehensive approach to personal player development and engaging group/team activities. Led by experienced coach Andy Skehan, our camps cater to both newcomers and seasoned players, offering expert guidance and a supportive environment to hone your skills and passion for rugby. Sign up now for an unforgettable experience on and off the field!{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <h1 class="hero-title ubuntu-regular">Camps</h1>
                <p class="ubuntu-light text-white">These camps provide a step-by-step process to personal player development and team activities that raise rugby IQ, new or experienced.</p>
                <p><a class="link light" href="https://twitter.com/andyskehan?lang=en">Meet coach Andy Skehan ></a></p>
            </div>
        </div>
    </div>
</div>
<div class="section-strip camps-wrapper">
    <div class="container">
        <div class="row">
            {% for camp in camps %}
            <div class="col-4">
                <div class="card-post">
                    <header class="card-header">
                        <h5 class="muted-heading">{{ camp.tags }}</h5>
                    </header>
                    <div class="card-content">
                        <h3 class="no-margin-top no-margin-bottom"><a class="link-soft underlined" href="">{{ camp.title }}</a></h3>
                        <p>{{ camp.description }}</p>
                    </div>
                    <div class="card-footer">
                        <p class="no-margin-bottom no-margin-top">Date: {{ camp.start_date|date:"F j" }} - {{ camp.end_date|date:"j" }}</p>
                    </div>
                </div>
            </div>
            {% empty %}
            <div class="col-4">
                <div class="card-post">
                    <header class="card-header">
                        <h5 class="muted-heading">Empty</h5>
                    </header>
                    <div class="card-content">
                        <h3 class="no-margin-top no-margin-bottom"><a class="link-soft underlined" href="">No Camps.</a></h3>
                        <p>Come back soon, no camps have been added yet.</p>
                    </div>
                    <div class="card-footer">
                        <p class="no-margin-bottom no-margin-top">Coming soon.</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

src/templates/camps/create.html
<!-- templates/camps/create.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/forms.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Create Camp{% endblock %}
{% block description %}Create a camp.{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <h1 class="hero-title ubuntu-regular">Create a Camp</h1>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for message in messages %}
                <p class="notification-title">{{ message }}</p>
            {% endfor %}
        </div>
    </div>
</div>
<div class="form-wrapper">
    <div class="container">
        <div class="row">
            <div class="form-container col-8 col-12-sm">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="button primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/camps/details.html
<!-- templates/camps/details.html -->
{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}

<!-- load the markdown filter -->
{% load camp_markdown_filter %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/camps/camp-details.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Camp Details{% endblock %}
{% block description %}Shows camp details for a specific rugby camp.{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <p class="text-white no-margin-bottom no-margin-top">{{ camp.start_date|date:"F j" }} - {{ camp.end_date|date:"j" }}</p>
                <h1 class="hero-title ubuntu-regular">{{camp.title}} Rugby Camp</h1>
                <p class="text-white"><i class="fa-solid fa-location-dot text-white"></i> <a href="https://www.google.com/maps/search/?api=1&query={{ camp.address }}" class="text-white" target="_blank">{{ camp.address }}</a></p>
                <div class="camp-image pb-1 center">
                    {% if camp.crest %}<img width="50%" src="{{ camp.crest.url }}" alt="{{ camp.title }} Crest">{% endif %}
                </div>
                <div class="text-white right">Player: ${{camp.player_price}} | Coach: ${{camp.coach_price}}</div>
                <hr>
                <div class="camp-details text-white">{{ camp.details | markdown | safe }}</div>
                <p class="text-white">Direct questions to <a class="text-white" href="mailto:rugbyvarsity@gmail.com">rugbyvarsity@gmail.com</a></p>
                <a class="button primary" href="{% url 'camps:select_camp_role' camp.id %}">Register</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/camps/error.html
<!-- templates/camps/error.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Camp Error{% endblock %}
{% block description %}Shows the user a camp related error{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <h1 class="hero-title ubuntu-regular">Scrum Collapse!</h1>
                <p class="ubuntu-light text-white">{{error_message}}</p>
            </div>
        </div>
    </div>
</div>
<div class="content-spacer">
</div>
{% endblock %}

src/templates/camps/index.html
<!-- templates/f5rugby/camps.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/camps/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/slider.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Rugby Camps{% endblock %}
{% block description %}Join our rugby camps for a comprehensive approach to personal player development and engaging group/team activities. Led by experienced coach Andy Skehan, our camps cater to both newcomers and seasoned players, offering expert guidance and a supportive environment to hone your skills and passion for rugby. Sign up now for an unforgettable experience on and off the field!{% endblock %}

{% block content %}
<div class="section white-grain">
    <div class="container">
        <div class="row">
            <div class="col-10 col-12-sm"> 
                <h1 class="section-title text-black">Rugby Camps</h1>
                <p class="section-subtitle text-black">Growing rugby & identifying talent across the USA. All ages & skill levels.</p>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="slider-controls">
                    <div class="slider-button for-light slider-left">
                        <i class="fa-solid fa-chevron-left"></i>
                    </div>
                    <div class="slider-button for-light slider-right">
                        <i class="fa-solid fa-chevron-right"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="slider-wrapper">
        <div class="slider">
            {% for camp in camps %}
            <a href="#" class="slider-card light">
                <div class="card-header">
                    <div class="card-topic">{{ camp.start_date|date:"F j" }}</div>
                    <div class="card-title">{{ camp.title }} camp</div>
                    <div class="card-desc">{{ camp.description }}</div>
                </div>
                <div class="card-img"><img src="{{ camp.crest.url }}" /></div>
            </a>
            {% endfor %}
            <div class="slider-card invisible"></div>
        </div>
    </div>
</div>
{% endblock %}

<!-- Custom JavaScript tags -->
{% block js %}
<script src="{% static 'js/camps/index.js' %}"></script>
<script src="{% static 'js/components/slider.js' %}"></script>
{% endblock %}

src/templates/camps/register_coach.html
<!-- templates/f5rugby/camps.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/forms.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Coach Register{% endblock %}
{% block description %}Join our rugby camps for a comprehensive approach to personal player development and engaging group/team activities. Led by experienced coach Andy Skehan, our camps cater to both newcomers and seasoned players, offering expert guidance and a supportive environment to hone your skills and passion for rugby. Sign up now for an unforgettable experience on and off the field!{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <h1 class="hero-title ubuntu-regular">{{ camp.title }} Camp Registration</h1>
                {% comment %}
                <p class="text-white">All {{type_string}} must download and sign the photo release and liability waiver to attend the camp. Then proceed to payment.</p>
                <p><a class="link light" href="{% static 'docs/photo_release_2024.pdf' %}" download>1. Photo Release PDF ></a></p>
                <p><a class="link light" href="{% static 'docs/liability_form_2024.pdf' %}" download>2. Liability Waiver PDF ></a></p>
                {% endcomment %}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-12">
            {% for message in messages %}
                <p class="notification-title">{{ message }}</p>
            {% endfor %}
        </div>
    </div>
</div>
<div class="form-wrapper">
    <div class="container">
        <div class="row">
            <div class="form-container col-8 col-12-sm">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input type="text" name="honeypot" style="display: none;">
                    <button type="submit" class="button primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/camps/register_success.html
<!-- templates/f5rugby/camps.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Register Success{% endblock %}
{% block description %}{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background content-spacer">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <h1 class="hero-title ubuntu-regular">Successfully registered!</h1>
                <h2 class="text-white">Proceed to payment.</h2>
                <p class="ubuntu-light text-white">You will not be able to attend the camp if you have not paid.</p>
                <a href="{{payment_link}}" class="button button primary">Proceed to Payment</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

src/templates/camps/select_role.html
<!-- templates/camps/select_role.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/camps/select_role.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Select Role{% endblock %}
{% block description %}Page that allows the user to select their role before registering for a rugby camp.{% endblock %}

{% block content %}
<div class="hero-wrapper blue-right-background">
    <div class="hero container">
        <div class="row">
            <div class="col-8">
                <p class="text-white">Direct questions to <a class="text-white" href="mailto:rugbyvarsity@gmail.com">rugbyvarsity@gmail.com</a></p>
                <h1 class="hero-title ubuntu-regular">Select a Role.</h1>
                <p class="ubuntu-light text-white">Are you a player or a coach?</p>
            </div>
        </div>
        <div class="row select-role-row">
            <div class="col">
                <p><a class="button primary" href="{% url 'camps:register_new' camp_id 'player' %}">Player</a></p>
            </div>
            <div class="col">
                <p><a class="button primary" href="{% url 'camps:register_new' camp_id 'coach' %}">Coach</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock %}