src/blog/urls.py
# blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.details, name='details'),
]

src/camp/urls.py
# camps/urls.py
from django.urls import path
from . import views

app_name = 'camps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:camp_id>/', views.details, name='details'),
    path('select-role/<int:camp_id>/', views.select_camp_role, name='select_camp_role'),
    path('register/<int:camp_id>/<str:register_type>/', views.register_stripe, name='register_new'),
    path('register-success/<path:payment_link>/', views.register_success, name='register_success'),
    path('edit-registration/<int:registration_id>/', views.edit_registration, name='edit_registration'),
    path('manager-panel/', views.manager_panel, name='manager_panel'),
    path('create/', views.create, name='create'),
]

src/f5rugby/urls.py
"""
URL configuration for f5rugby project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('preview/', views.preview, name='preview'),
    path('camps/', include('camp.urls')),
    path('health/', include('health.urls')),
    path('tours/', include('tour.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('account.urls')),
    path('deploy-webhook/', views.webhook_handler, name='deploy_webhook'),
    path('success/', views.success_page, name='success_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/templates/components/footer.html
<!-- templates/components/footer.html -->

src/templates/components/navigation.html
<!-- templates/components/navigation.html -->
<div class="navmenu">
    <a class="navlink" href="{% url 'index' %}">Home</a>
    <a class="navlink" href="{% url 'camps:index' %}">Camps</a>
    <a class="navlink" href="">Tours</a>
    <a class="navlink" href="">Health</a>
    <a class="navlink" href="">Store</a>
</div>

<div class="navbar">
    <span class="menulink">Try</span>      
</div>