src/account/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.logon, name='login'),
    path('logout/', views.logoff, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('camps/admin/', views.camps_admin, name='camps_admin')
]

src/blog/urls.py
# blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:article_id>/', views.details, name='details'),
]

src/camp/urls.py
# camps/urls.py
from django.urls import path
from . import views

app_name = 'camps'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:camp_id>/', views.details, name='details'),
    path('select-role/<int:camp_id>/', views.select_camp_role, name='select_camp_role'),
    path('register/<int:camp_id>/<str:register_type>/', views.register_stripe, name='register_new'),
    path('register-success/<path:payment_link>/', views.register_success, name='register_success'),
    path('edit-registration/<int:registration_id>/', views.edit_registration, name='edit_registration'),
    path('manager-panel/', views.manager_panel, name='manager_panel'),
    path('create/', views.create, name='create'),
]

src/f5rugby/urls.py
"""
URL configuration for f5rugby project.
"""
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from . import views
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('preview/', views.preview, name='preview'),
    path('camps/', include('camp.urls')),
    path('health/', include('health.urls')),
    path('tours/', include('tour.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('account.urls')),
    path('deploy-webhook/', views.webhook_handler, name='deploy_webhook'),
    path('success/', views.success_page, name='success_page'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/account/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass

src/account/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import User
from django import forms

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

class LoginForm(forms.Form):
    username = forms.CharField(max_length=150)
    password = forms.CharField(widget=forms.PasswordInput)

src/account/views.py
from django.db.models import Q
from django.contrib import messages
from .forms import SignUpForm, LoginForm
from .decorators import manager_required
from django.shortcuts import render, redirect
from camp.models import Camp, GeneralRegistration
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        honeypot = request.POST.get('honeypot', '')
        password = request.POST.get('password', '')

        if form.is_valid() and not honeypot:
            form.save()
            return render(request, 'accounts/signup_success.html')
        else:
            if honeypot:
                error_message = 'Alert: Bot detected! This incident will be reported to the administrator.'
                messages.error(request, error_message)
            else:
                error_message = 'Correct the errors below.'
                messages.error(request, error_message)
    else:
        form = SignUpForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/signup.html', context)

def logon(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('index')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = LoginForm()

    context = {
        'form': form,
    }

    return render(request, 'accounts/login.html', context)

def logoff(request):
    logout(request)
    return redirect('index')

@login_required
def dashboard(request):
    user = request.user

    context = {
        'motd': 'Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and most of all, love of what you are doing or learning to do.',
    }
    
    # Check if the user belongs to a specific group
    if user.groups.filter(name='Manager').exists():
        return render(request, 'accounts/admin_dashboard.html', context)
    elif user.groups.filter(name='Trainer').exists():
        return render(request, 'accounts/trainer_dashboard.html', context)
    else:
        return render(request, 'accounts/default_dashboard.html', context)

@login_required
@manager_required
def camps_admin(request):
    camps = Camp.objects.all()
    registrations = GeneralRegistration.objects.all()
    collapsed = True

    # Filter by search query
    search_query = request.GET.get('search')
    if search_query:
        registrations = registrations.filter(
            Q(first_name__icontains=search_query) |
            Q(last_name__icontains=search_query) |
            Q(email__icontains=search_query)
        )
        collapsed = False

    # Filter by type
    type_filter = request.GET.get('type')
    if type_filter:
        registrations = registrations.filter(type=type_filter)
        collapsed = False

    # Filter by paid status
    paid_filter = request.GET.get('paid')
    if paid_filter in ['true', 'false']:
        registrations = registrations.filter(has_paid=(paid_filter == 'true'))
        collapsed = False

    camp_title_filter = request.GET.get('camp_title')
    if camp_title_filter:
        registrations = registrations.filter(camp__title__icontains=camp_title_filter)
        collapsed = False
    
        
    # Calculate revenue and other statistics
    total_revenue = 0
    total_coaches = 0
    total_players = 0
    for registration in registrations:
        if registration.type == 'coach':
            total_revenue += registration.camp.coach_price
            total_coaches += 1
        elif registration.type == 'player':
            total_revenue += registration.camp.player_price
            total_players += 1

    context = {
        'registrations': registrations,
        'total_revenue': total_revenue,
        'total_players': total_players,
        'total_coaches': total_coaches,
        'camps': camps,
        'collapsed': collapsed,
    }
    return render(request, 'accounts/camps_admin/camps_overview.html', context)

src/templates/accounts/camps_admin/camps_overview.html
<!-- templates/accounts/camps_summary.html -->

{% extends 'f5rugby/base.html' %}

<!-- load the static tag -->
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/f5rugby/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/camps/camps_summary.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/cards.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/components/tables.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
{% endblock %}

{% block title %}Admin Camps{% endblock %}
{% block description %}Admin summary page for camps.{% endblock %}

{% block content %}
<div class="pt-4 pb-3">
    <div class="container content-spacer">
        <div class="row">
            <h1 class="ubuntu-regular">Camps Summary</h1>
            <p>Insight on camp registrations.</p>
        </div>
        <div class="row pt-1 pb-2">
            <p><a class="button primary" href="{% url 'camps:create' %}">Add Camp +</a></p>
        </div>
        <div class="row pt-1 pb-2">
            <div class="col-4">
                <div class="card-metric">
                    <header class="card-header border-top-green">
                        <h5 class="muted-heading">Finance</h5>
                    </header>
                    <div class="card-content">
                        <h4 class="no-margin-top no-margin-bottom">Projected Revenue</h4>
                        <div class="row">
                            <div class="col-12">
                                <h4 class="right no-margin-top no-margin-bottom">${{total_revenue}}.00</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card-metric">
                    <header class="card-header border-top-orange">
                        <h5 class="muted-heading">Metrics</h5>
                    </header>
                    <div class="card-content">
                        <h4 class="no-margin-top no-margin-bottom">Total Players</h4>
                        <div class="row">
                            <div class="col-12">
                                <h4 class="right no-margin-top no-margin-bottom">{{total_players}}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="card-metric">
                    <header class="card-header border-top-orange">
                        <h5 class="muted-heading">Metrics</h5>
                    </header>
                    <div class="card-content">
                        <h4 class="no-margin-top no-margin-bottom">Total Coaches</h4>
                        <div class="row">
                            <div class="col-12">
                                <h4 class="right no-margin-top no-margin-bottom">{{total_coaches}}</h4>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <a class="link black" href="#" id="toggle-filters">Filters ></a>
            </div>
            <div class="col-12 {% if collapsed %}collapsed{% endif %}" id="filter-form-wrapper">
                <form id="filter-form" class="pt-2" method="GET" action="">
                    <div class="row">
                        <div class="col">
                            <label for="search">Search:</label>
                            <input type="text" id="search" name="search" placeholder="name or email" value="{{ request.GET.search }}">
                        </div>
                        <div class="col">
                            <label for="camp_title">Camp:</label>
                            <input type="text" id="camp_title" name="camp_title" value="{{ request.GET.camp_title }}" placeholder="camp title">
                        </div>
                        <div class="col">
                            <label for="type">Type:</label>
                            <select id="type" name="type">
                                <option value="">All</option>
                                <option value="coach" {% if request.GET.type == 'coach' %}selected{% endif %}>Coach</option>
                                <option value="player" {% if request.GET.type == 'player' %}selected{% endif %}>Player</option>
                            </select>
                        </div>
                        <div class="col">
                            <label for="paid">Paid:</label>
                            <select id="paid" name="paid">
                                <option value="">All</option>
                                <option value="true" {% if request.GET.paid == 'true' %}selected{% endif %}>Paid</option>
                                <option value="false" {% if request.GET.paid == 'false' %}selected{% endif %}>Not Paid</option>
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 right">
                            <div>
                                <button class="button primary" type="submit">Filter</button>
                                <button class="button clear" type="button" id="clear-button">Clear</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <div class="col-12 table-wrapper">
                <table id="camps-table">
                    <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Camp Title</th>
                            <th>Email</th>
                            <th>Type</th>
                            <th>Photo Release Form</th>
                            <th>Liability Waiver</th>
                            <th>Paid</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for registration in registrations %}
                        <tr data-record-id="{{ registration.id }}">
                            <td><a href="{% url 'camps:edit_registration' registration.id %}">{{ registration.first_name }}</a></td>
                            <td>{{ registration.last_name }}</td>
                            <td>{{ registration.camp.title }}</td>
                            <td>{{ registration.email }}</td>
                            <td>{{ registration.type }}</td>
                            <td>{% if registration.photo_release_form %}<a href="{{ registration.photo_release_form.url }}" target="_blank"><i class="fa-solid fa-file-arrow-down"></i></a>{% else %}-{% endif %}</td>
                            <td>{% if registration.liability_waiver %}<a href="{{ registration.liability_waiver.url }}" target="_blank"><i class="fa-solid fa-file-arrow-down"></i></a>{% else %}-{% endif %}</td>
                            <td>{% if registration.has_paid %}<i class="fa-regular fa-circle-check text-green"></i>{% else %}<i class="fa-regular fa-circle-xmark text-red"></i>{% endif %}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

<!-- Custom JavaScript tags -->
{% block js %}
<script src="{% static 'js/camps/camps_summary.js' %}"></script>
<script src="{% static 'js/components/filters.js' %}"></script>
{% endblock %}